### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by p7e4** [tr3ee/go-rjsocks#13]
golang版本1.12.5 
\# github.com/tr3ee/go-rjsocks/core
..\core\handle.go:71:33: cannot use &fillLayer (type *RawLayer) as type gopacket.SerializableLayer in argument to h.send:
        *RawLayer does not implement gopacket.SerializableLayer (missing LayerType method)
..\core\handle.go:95:39: cannot use &fillLayer (type *RawLayer) as type gopacket.SerializableLayer in argument to h.send:
        *RawLayer does not implement gopacket.SerializableLayer (missing LayerType method)
..\core\handle.go:125:39: cannot use &fillLayer (type *RawLayer) as type gopacket.SerializableLayer in argument to h.send:
        *RawLayer does not implement gopacket.SerializableLayer (missing LayerType method)
..\core\handle.go:169:33: cannot use &echo (type *RawLayer) as type gopacket.SerializableLayer in argument to h.send:
        *RawLayer does not implement gopacket.SerializableLayer (missing LayerType method)

**Comment by tr3ee** [comment]
这是gopacket库升级之后接口不兼容导致的，预计在这个月内推出下个版本更新

**Comment by p7e4** [comment]
使用gopacket.Payload代替RawLayer

**Comment by tr3ee** [comment]
酷👍有想法提交一个PR吗？


 
---原始邮件---
发件人: "p7e4"<notifications@github.com>
发送时间: 2019年7月6日(星期六) 晚上10:45
收件人: "tr3ee/go-rjsocks"<go-rjsocks@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"tr3e"<807596654@qq.com>;
主题: Re: [tr3ee/go-rjsocks] 编译失败 (#13)



使用gopacket.Payload代替RawLayer
