### ISSUE TITLE
账号a密码a，输入认证，结果报文封装的用户名带乱码

### ISSUE THREAD

**Issue by lazebird** [tr3ee/go-rjsocks#6]
如题

**Comment by tr3ee** [comment]
这是由于目前校园网大部分使用某公司的产品，其所实现的EAP协议中，包含了一些非公开的结构，并且固定了Identity的长度为0x10

可修改[SendResponseIdentity](https://github.com/tr3ee/go-rjsocks/blob/master/core/handle.go#L93)符合特定需求

抱歉一周后才回复 :(
